[package]
name = "lox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.61"
# for the repl
rustyline = "14.0.0"
mucow = "0.1.0"
fnv = "1.0.7"
